
module.exports = {
    env: { es2024: true },
    parserOptions: {
        ecmaFeatures: { impliedStrict: true },
        sourceType: 'module',
    },
    rules: {
        // Best practices
        'arrow-body-style': 'warn',
        'camelcase': ['warn', { ignoreGlobals: true, ignoreImports: true }],
        'func-style': ['warn', 'declaration', { allowArrowFunctions: true }],
        'logical-assignment-operators': 'warn',
        'max-params': ['warn', { 'max': 4 }],
        'multiline-comment-style': 'warn',
        'new-cap': ['warn', { capIsNew: false, properties: true }],
        'no-case-declarations': 'warn',
        'no-delete-var': 'warn',
        'no-else-return': 'warn',
        'no-empty': 'warn',
        'no-extra-boolean-cast': 'warn',
        'no-extra-semi': 'warn',
        'no-floating-decimal': 'warn',
        'no-global-assign': 'warn',
        'no-lonely-if': 'warn',
        'no-mixed-operators': 'warn',
        'no-negated-condition': 'warn',
        'no-nonoctal-decimal-escape': 'warn',
        'no-octal': 'warn',
        'no-redeclare': 'warn',
        'no-regex-spaces': 'warn',
        'no-shadow-restricted-names': 'warn',
        'no-unused-labels': 'warn',
        'no-useless-catch': 'warn',
        'no-useless-escape': 'warn',
        'no-with': 'warn',
        'object-shorthand': 'warn',
        'operator-assignment': 'warn',
        'prefer-arrow-callback': 'warn',
        'prefer-const': ['warn', { destructuring: 'all' }],
        'prefer-template': 'warn',
        'quote-props': ['warn', 'consistent-as-needed'],
        'require-yield': 'warn',
        'sort-imports': 'warn',
        'sort-keys': 'warn',
        // Errors
        'constructor-super': 'warn',
        'for-direction': 'warn',
        'getter-return': 'warn',
        'no-async-promise-executor': 'warn',
        'no-class-assign': 'warn',
        'no-compare-neg-zero': 'warn',
        'no-cond-assign': 'warn',
        'no-const-assign': 'warn',
        'no-constant-condition': 'warn',
        'no-control-regex': 'warn',
        'no-debugger': 'warn',
        'no-dupe-args': 'warn',
        'no-dupe-class-members': 'warn',
        'no-dupe-else-if': 'warn',
        'no-dupe-keys': 'warn',
        'no-duplicate-case': 'warn',
        'no-duplicate-imports': 'warn',
        'no-empty-character-class': 'warn',
        'no-empty-pattern': 'warn',
        'no-ex-assign': 'warn',
        'no-fallthrough': 'warn',
        'no-func-assign': 'warn',
        'no-import-assign': 'warn',
        'no-inner-declarations': 'warn',
        'no-invalid-regexp': 'warn',
        'no-irregular-whitespace': 'warn',
        'no-loss-of-precision': 'warn',
        'no-misleading-character-class': 'warn',
        'no-new-symbol': 'warn',
        'no-obj-calls': 'warn',
        'no-prototype-builtins': 'warn',
        'no-self-assign': 'warn',
        'no-setter-return': 'warn',
        'no-sparse-arrays': 'warn',
        'no-this-before-super': 'warn',
        'no-undef': 'warn',
        'no-unexpected-multiline': 'warn',
        'no-unreachable': 'warn',
        'no-unsafe-finally': 'warn',
        'no-unsafe-negation': 'warn',
        'no-unsafe-optional-chaining': 'warn',
        'no-unused-vars': ['warn', { ignoreRestSiblings: true }],
        'no-useless-backreference': 'warn',
        'use-isnan': 'warn',
        'valid-typeof': 'warn',
        // Style
        'array-bracket-newline': ['warn', 'consistent'],
        'array-bracket-spacing': 'warn',
        'array-element-newline': ['warn', 'consistent'],
        'arrow-parens': ['warn', 'as-needed'],
        'arrow-spacing': 'warn',
        'block-spacing': 'warn',
        'brace-style': 'warn',
        'comma-dangle': ['warn', 'always-multiline'],
        'comma-spacing': 'warn',
        'comma-style': 'warn',
        'computed-property-spacing': 'warn',
        'dot-location': ['warn', 'property'],
        'eol-last': 'warn',
        'func-call-spacing': 'warn',
        'function-call-argument-newline': ['warn', 'consistent'],
        'generator-star-spacing': ['warn', 'after'],
        'indent': ['warn', 4, { MemberExpression: 'off', SwitchCase: 1 }],
        'jsx-quotes': 'warn',
        'key-spacing': ['warn', { mode: 'minimum' }],
        'keyword-spacing': 'warn',
        'linebreak-style': 'warn',
        'new-parens': 'warn',
        'no-mixed-spaces-and-tabs': 'warn',
        'no-multi-spaces': ['warn', {
            'exceptions': {
                ImportDeclaration: true,
                Property: true,
                VariableDeclarator: true,
            }
        }],
        'no-trailing-spaces': 'warn',
        'no-whitespace-before-property': 'warn',
        'object-curly-newline': 'warn',
        'object-curly-spacing': ['warn', 'always'],
        'object-property-newline': ['warn', { allowAllPropertiesOnSameLine: true }],
        'operator-linebreak': ['warn', 'before', { overrides: { '=': 'after' } }],
        'quotes': ['warn', 'single', { avoidEscape: true }],
        'rest-spread-spacing': 'warn',
        'semi': ['warn', 'never'],
        'space-before-blocks': 'warn',
        'space-before-function-paren': ['warn', { named: 'never' }],
        'space-in-parens': 'warn',
        'space-infix-ops': 'warn',
        'space-unary-ops': 'warn',
        'switch-colon-spacing': 'warn',
        'template-curly-spacing': 'warn',
        'template-tag-spacing': 'warn',
        'yield-star-spacing': 'warn',
    },
}
