
module.exports = {
    extends: ['@cdoublev/eslint-config'],
    parserOptions: {
        ecmaFeatures: { jsx: true },
    },
    plugins: ['react', 'react-hooks'],
    rules: {
        'jsx-quotes': ['warn', 'prefer-single'],
        'react/display-name': 'warn',
        'react/jsx-key': 'warn',
        'react/jsx-no-comment-textnodes': 'warn',
        'react/jsx-no-duplicate-props': 'warn',
        'react/jsx-no-target-blank': 'warn',
        'react/jsx-no-undef': 'warn',
        'react/jsx-uses-react': 'warn',
        'react/jsx-uses-vars': 'warn',
        'react/no-children-prop': 'warn',
        'react/no-danger-with-children': 'warn',
        'react/no-deprecated': 'warn',
        'react/no-direct-mutation-state': 'warn',
        'react/no-find-dom-node': 'warn',
        'react/no-is-mounted': 'warn',
        'react/no-render-return-value': 'warn',
        'react/no-string-refs': 'warn',
        'react/no-unescaped-entities': ['warn', { forbid: [
            { char: '>', alternatives: ['&gt;'] },
            { char: '}', alternatives: ['&#125;'] },
        ]}],
        'react/no-unknown-property': 'warn',
        'react/prop-types': 'warn',
        'react/react-in-jsx-scope': 'warn',
        'react/require-render-return': 'warn',
        'react-hooks/exhaustive-deps': 'warn',
        'react-hooks/rules-of-hooks': 'warn',
    },
    settings: {
        react: { version: 'detect' },
    },
}
